version: 2
updates:
  # NPM
  - directory: /
    groups:
      emotion:
        emotion: ["@emotion/*"]
      eslint:
        patterns: ["@typescript-eslint/*", "eslint", "eslint-*"]
      react:
        patterns: ["react", "react-dom"]
      stylelint:
        patterns: ["postcss-css-in-js", "stylelint", "stylelint-*"]
      typescript:
        patterns: ["typescript", "@types"]
      vite:
        patterns: ["@vitejs/*", "vite", "vite-*"]
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    versioning-strategy: increase-if-necessary
